apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-search
  labels:
    customer: airtrip
spec:
  selector:
    matchLabels:
      app: search
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - image: nguyenminh/air_search:0.01
        name: air-search
        ports:
        - containerPort: 8080